version: "3"
services:
  db1:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=xiaobaitu2
    volumes:
      - ./data1:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  db2:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=xiaobaitu2
    volumes:
      - ./data2:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always


networks: {default: {external: {name: learn}}}
